server:
  port: 8802
spring:
  application:
    name: auth-center
  datasource:
    url: jdbc:mysql://****.****.****:3306/****?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ****
    password: ****
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      
mybatis:
  type-aliases-package: com.cloud.mapper
  mapper-locations:
  - classpath:/mapper/**/*Mapper.xml
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://****.****.****:8761/eureka
      
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: INFO
  file: app.log
     
