server:
  port: 8801
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://****.****.****:3306/****?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j3a402.p.ssafy.io:8761/eureka
#      defaultZone: http://localhost:8761/eureka

zuul:
  ignored-headers:
  - Access-Control-Allow-Credentials
  - Access-Control-Allow-Origin
  routes:
   service-user:
     path: /users/**
     service-id: users
   service-product:
     path: /products/**
     service-id: products
   service-auth:
     path: /auth/**
     service-id: auth-center
     sensitive-headers:
      - 
   service-file:
      path: /images/**
      service-id: images
      sensitive-headers:
      - 
   service-campaign:
      path: /campaigns/**
      service-id: campaigns
     
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: INFO
  file:
    path: /logging
    name: /logging/API-Gateway.log
  
